[2024-05-03T11:22:29.769+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T11:22:29.778+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bharat1_dag.inaccurate scheduled__2024-05-03T04:30:00+00:00 [queued]>
[2024-05-03T11:22:29.781+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bharat1_dag.inaccurate scheduled__2024-05-03T04:30:00+00:00 [queued]>
[2024-05-03T11:22:29.781+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-03T11:22:29.789+0530] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-03 04:30:00+00:00
[2024-05-03T11:22:29.791+0530] {standard_task_runner.py:63} INFO - Started process 9058 to run task
[2024-05-03T11:22:29.792+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bharat1_dag', 'inaccurate', 'scheduled__2024-05-03T04:30:00+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/bharat1_dag.py', '--cfg-path', '/tmp/tmpllna3mfv']
[2024-05-03T11:22:29.793+0530] {standard_task_runner.py:91} INFO - Job 237: Subtask inaccurate
[2024-05-03T11:22:29.810+0530] {task_command.py:426} INFO - Running <TaskInstance: bharat1_dag.inaccurate scheduled__2024-05-03T04:30:00+00:00 [running]> on host ninebit5lm
[2024-05-03T11:22:29.837+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bharat1_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T04:30:00+00:00'
[2024-05-03T11:22:29.838+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T11:22:29.838+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T11:22:29.838+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-03T11:22:29.841+0530] {subprocess.py:86} INFO - Output:
[2024-05-03T11:22:29.842+0530] {subprocess.py:93} INFO - inaccurate
[2024-05-03T11:22:29.842+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-03T11:22:29.842+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T11:22:29.850+0530] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=bharat1_dag, task_id=inaccurate, execution_date=20240503T043000, start_date=20240503T055229, end_date=20240503T055229
[2024-05-03T11:22:29.884+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T11:22:29.893+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T11:22:29.893+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
