[2024-05-03T15:18:33.186+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T15:18:33.193+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T09:48:29.266667+00:00 [queued]>
[2024-05-03T15:18:33.195+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T09:48:29.266667+00:00 [queued]>
[2024-05-03T15:18:33.195+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-03T15:18:33.202+0530] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-03 09:48:29.266667+00:00
[2024-05-03T15:18:33.204+0530] {standard_task_runner.py:63} INFO - Started process 76082 to run task
[2024-05-03T15:18:33.205+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_api_data', 'fetch_data', 'manual__2024-05-03T09:48:29.266667+00:00', '--job-id', '856', '--raw', '--subdir', 'DAGS_FOLDER/async_api_dag.py', '--cfg-path', '/tmp/tmpilon8648']
[2024-05-03T15:18:33.206+0530] {standard_task_runner.py:91} INFO - Job 856: Subtask fetch_data
[2024-05-03T15:18:33.220+0530] {task_command.py:426} INFO - Running <TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T09:48:29.266667+00:00 [running]> on host ninebit5lm
[2024-05-03T15:18:33.252+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_api_data' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T09:48:29.266667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T09:48:29.266667+00:00'
[2024-05-03T15:18:33.252+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T15:18:33.252+0530] {python.py:237} INFO - Done. Returned value was: <coroutine object fetch_data at 0x7f57a9749d20>
[2024-05-03T15:18:33.253+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T15:18:33.254+0530] {xcom.py:677} ERROR - Object of type coroutine is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-05-03T15:18:33.254+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/usr/local/lib/python3.10/dist-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'coroutine'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 3182, in xcom_push
    XCom.set(
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/xcom.py", line 675, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/dist-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable
[2024-05-03T15:18:33.255+0530] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_api_data, task_id=fetch_data, execution_date=20240503T094829, start_date=20240503T094833, end_date=20240503T094833
[2024-05-03T15:18:33.260+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 856 for task fetch_data (Object of type coroutine is not JSON serializable; 76082)
[2024-05-03T15:18:33.297+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T15:18:33.309+0530] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T15:18:33.309+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
