[2024-07-02T12:53:01.166+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-02T12:53:01.172+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bharat_cgpa.sem_8_cgpa manual__2024-07-02T07:22:47.430682+00:00 [queued]>
[2024-07-02T12:53:01.174+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bharat_cgpa.sem_8_cgpa manual__2024-07-02T07:22:47.430682+00:00 [queued]>
[2024-07-02T12:53:01.174+0530] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-02T12:53:01.181+0530] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): sem_8_cgpa> on 2024-07-02 07:22:47.430682+00:00
[2024-07-02T12:53:01.183+0530] {standard_task_runner.py:63} INFO - Started process 12088 to run task
[2024-07-02T12:53:01.185+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bharat_cgpa', 'sem_8_cgpa', 'manual__2024-07-02T07:22:47.430682+00:00', '--job-id', '1226', '--raw', '--subdir', 'DAGS_FOLDER/cgpa1.py', '--cfg-path', '/tmp/tmpflox2e7d']
[2024-07-02T12:53:01.185+0530] {standard_task_runner.py:91} INFO - Job 1226: Subtask sem_8_cgpa
[2024-07-02T12:53:01.200+0530] {task_command.py:426} INFO - Running <TaskInstance: bharat_cgpa.sem_8_cgpa manual__2024-07-02T07:22:47.430682+00:00 [running]> on host ninebit5lm
[2024-07-02T12:53:01.226+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bharat_cgpa' AIRFLOW_CTX_TASK_ID='sem_8_cgpa' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T07:22:47.430682+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-02T07:22:47.430682+00:00'
[2024-07-02T12:53:01.227+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-02T12:53:01.227+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-02T12:53:01.227+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bharat/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sem1_GPA() missing 1 required positional argument: 'sem1_marks'
[2024-07-02T12:53:01.229+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bharat_cgpa, task_id=sem_8_cgpa, run_id=manual__2024-07-02T07:22:47.430682+00:00, execution_date=20240702T072247, start_date=20240702T072301, end_date=20240702T072301
[2024-07-02T12:53:01.234+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1226 for task sem_8_cgpa (sem1_GPA() missing 1 required positional argument: 'sem1_marks'; 12088)
[2024-07-02T12:53:01.276+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-02T12:53:01.286+0530] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-02T12:53:01.287+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
